### ISSUE TITLE
Errors with search and tag of data object

### ISSUE THREAD

**Issue by michael-conway** [angrygoat/DE#39]
Err_not_unique adding a tag in DE, unable to contact master.

These seem like various related errors showing up as dialogs in DE with these associated service box log messages 

See attached log.
[tag_logs.txt](https://github.com/angrygoat/DE/files/433167/tag_logs.txt)

**Comment by michael-conway** [comment]
![image](https://cloud.githubusercontent.com/assets/1097261/17902942/7315a7b0-6937-11e6-904d-3d7d67641889.png)
[tag_logs2.txt](https://github.com/angrygoat/DE/files/433177/tag_logs2.txt)

**Comment by michael-conway** [comment]
note messages in /var/log/elasticsearch/elasticsearch.log on esearch machine

```
[2016-08-23 14:01:42,951][WARN ][transport.netty          ] [node-dfc-de-esearch] exception caught on transport layer [[id: 0x29d490f3]], closing connection
java.nio.channels.UnresolvedAddressException
        at sun.nio.ch.Net.checkAddress(Net.java:107)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:649)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:574)
        at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:634)
        at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
        at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
        at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannelsLight(NettyTransport.java:689)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:652)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNodeLight(NettyTransport.java:619)
        at org.elasticsearch.transport.TransportService.connectToNodeLight(TransportService.java:150)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$3.run(UnicastZenPing.java:286)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
(END)


```

this shows up as a 503 in terrain logs
