### ISSUE TITLE
issue running sharkbait against UNC/alternative user to de_grouper

### ISSUE THREAD

**Issue by michael-conway** [angrygoat/DE#44]
initial issue is a stacktrace running facepalm against unc ldap per Don S

This follows on the heels of a drop/create on the DE database, then
facepalm, then sharkbait:

[dls@visr-de-grouper ~]$ java -jar sharkbait-standalone-patched.jar -h
host -d db -U user -e de --grouper-user auser
WARNING: update already refers to: #'clojure.core/update in namespace:
sharkbait.db, being replaced by: #'honeysql.helpers/update
WARNING: read already refers to: #'clojure.core/read in namespace:
sharkbait.permissions, being replaced by: #'sharkbait.permissions/read
visrdedb password:
Grouper starting up: version: 2.2.1, build date: null, env: <no label
configured>
grouper.properties read from:
/home/dls/file:/home/dls/sharkbait-standalone-patched.jar!/grouper.properties
Grouper current directory is: /home/dls
log4j.properties read from:
/home/dls/file:/home/dls/sharkbait-standalone-patched.jar!/log4j.properties
Grouper is logging to file:   console, at min level WARN for package:
edu.internet2.middleware.grouper, based on log4j.properties
grouper.hibernate.properties:
/home/dls/file:/home/dls/sharkbait-standalone-patched.jar!/grouper.hibernate.properties
grouper.hibernate.properties: null@null
sources.xml read from:         [cant find sources.xml]
sources.xml groupersource id: g:gsa
sources.xml ldap source id:   xxx:
pid=xxx,ou=People,xx
sources.xml groupersource id: grouperEntities
2016-09-08 15:17:15,571: [main] WARN
GrouperStartup.printConfigOnce(167) -  - Grouper starting up: version:
2.2.1, build date: null, env: <no label configured>
Grouper warning: Not checking configuration integrity due to
grouper.properties: configuration.detect.errors
2016-09-08 15:17:19,062: [main] WARN
GrouperCheckConfig.configCheckDisabled(296) -  - Not checking
configuration integrity due to grouper.properties:
configuration.detect.errors
Loading DE subjects...
"Elapsed time: 43.457912 msecs"
Registering DE users...
2016-09-08 15:20:08,304: [main] ERROR GroupFinder.findByName(291) -  -
error finding group by name: subject cannot VIEW, name:
iplant:de:de:users:de-users
Exception in thread "main"
edu.internet2.middleware.grouper.exception.InsufficientPrivilegeException:
subject cannot CREATE, stem name: iplant:de:de:users, group extension:
de-users, group dExtension: de-users, uuid: null, typeOfGroup: role,
9506c1657c8e480da72b7c9397b601be,'dls','person',
Problem in HibernateSession: HibernateSession (6b8cb5cd): notNew,
notReadonly, READ_WRITE_NEW, activeTransaction, session (36a0a0a9),
Problem in HibernateSession: HibernateSession (9392df5): notNew,
notReadonly, READ_WRITE_NEW, activeTransaction, session (36a0a0a9),
Problem in HibernateSession: HibernateSession (14164c73): new,
notReadonly, READ_WRITE_NEW, notActiveTransaction, session (36a0a0a9),
Problem saving group: iplant:de:de:users:de-users, thread: 6443859
    at edu.internet2.middleware.grouper.Stem$5.callback(Stem.java:2246)
    at edu.internet2.middleware.grouper.hibernate.HibernateSession.callbackHibernateSession(HibernateSession.java:654)
    at edu.internet2.middleware.grouper.Stem.internal_addChildGroup(Stem.java:2229)
    at edu.internet2.middleware.grouper.Stem.internal_addChildGroup(Stem.java:2201)
    at edu.internet2.middleware.grouper.Stem$15.callback(Stem.java:4230)
    at edu.internet2.middleware.grouper.hibernate.HibernateSession.callbackHibernateSession(HibernateSession.java:654)
    at edu.internet2.middleware.grouper.Stem.internal_addChildRole(Stem.java:4223)
    at edu.internet2.middleware.grouper.GroupSave$1$1.callback(GroupSave.java:523)
    at edu.internet2.middleware.grouper.GrouperSession.callbackGrouperSession(GrouperSession.java:974)
    at edu.internet2.middleware.grouper.GroupSave$1.callback(GroupSave.java:415)
    at edu.internet2.middleware.grouper.internal.dao.hib3.Hib3TransactionDAO$1.callback(Hib3TransactionDAO.java:66)
    at edu.internet2.middleware.grouper.hibernate.HibernateSession.callbackHibernateSession(HibernateSession.java:654)
    at edu.internet2.middleware.grouper.internal.dao.hib3.Hib3TransactionDAO.transactionCallback(Hib3TransactionDAO.java:56)
    at edu.internet2.middleware.grouper.hibernate.GrouperTransaction.callbackGrouperTransaction(GrouperTransaction.java:87)
    at edu.internet2.middleware.grouper.hibernate.GrouperTransaction.callbackGrouperTransaction(GrouperTransaction.java:106)
    at edu.internet2.middleware.grouper.GroupSave.save(GroupSave.java:406)
    at sharkbait.roles$create_role.invoke(roles.clj:14)
    at sharkbait.users$register_de_users.invoke(users.clj:10)
    at sharkbait.core$register_de_users.invoke(core.clj:53)
    at sharkbait.core$register_de_entities.invoke(core.clj:77)
    at sharkbait.core$perform_de_user_actions.invoke(core.clj:89)
    at sharkbait.core$_main.doInvoke(core.clj:100)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at sharkbait.core.main(Unknown Source)

**Comment by michael-conway** [comment]
error in sharkbait core.clj ~ line 49

``` clojure

(defn- register-de-users
  "Adds all DE users to the de-users group."
  [session folder-names subjects]
  (println "Registering DE users...")
  (users/register-de-users session (:de-users folder-names) subjects))


```

trying to add the users in de to the de-users grouper folder....

calls GroupSave with a session

http://www.internet2.edu/grouper/release/1.5.0/doc/api/index.html?edu/internet2/middleware/grouper/GroupSave.html
